/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * WebApp
 * OpenAPI spec version: v1
 */

export interface CreateUserRequest {
  email: string;
  userName: string;
  password: string;
  confirmPassword: string;
}
