/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * WebApp
 * OpenAPI spec version: v1
 */

export type GetApiContestsParams = { Filters?: string; Sorts?: string; Page?: number; PageSize?: number };
