/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * WebApp
 * OpenAPI spec version: v1
 */

export interface IndexContestsResponse {
  id?: number;
  topic?: string | null;
  description?: string | null;
  startDate?: string;
  endDate?: string;
  thumbnailUrl?: string | null;
}
