/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * WebApp
 * OpenAPI spec version: v1
 */
import type { IndexContestEntriesResponseCorrection } from './indexContestEntriesResponseCorrection';
import type { IndexContestEntriesResponseTeam } from './indexContestEntriesResponseTeam';

export interface IndexContestEntriesResponse {
  id?: number;
  correction?: IndexContestEntriesResponseCorrection;
  team?: IndexContestEntriesResponseTeam;
}
