/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * WebApp
 * OpenAPI spec version: v1
 */
import type { LoginResponseUser } from './loginResponseUser';

export interface LoginResponse {
  user?: LoginResponseUser;
}
