/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * WebApp
 * OpenAPI spec version: v1
 */

export interface LoginResponseUser {
  id?: string | null;
  email?: string | null;
  userName?: string | null;
  roles?: string[] | null;
}
