/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * WebApp
 * OpenAPI spec version: v1
 */

export type PostApiContestsBody = {
  Topic: string;
  Description: string;
  MaxPoints: number;
  Exercise: Blob;
  TopicHelp?: Blob;
  Thumbnail?: Blob;
  StartDate: string;
  EndDate: string;
};
