/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * WebApp
 * OpenAPI spec version: v1
 */

export interface UpdateUserRequest {
  userName: string;
  email?: string | null;
  newPassword?: string | null;
  confirmNewPassword?: string | null;
  currentPassword?: string | null;
}
