/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * WebApp
 * OpenAPI spec version: v1
 */
import type { UserResponseTeamUser } from './userResponseTeamUser';

export interface UserResponseTeam {
  id?: number;
  name?: string | null;
  points?: number;
  creatorId?: string | null;
  members?: UserResponseTeamUser[] | null;
}
