/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * WebApp
 * OpenAPI spec version: v1
 */
import type { UserResponseTeam } from './userResponseTeam';

export interface UserResponse {
  id?: string | null;
  email?: string | null;
  userName?: string | null;
  team?: UserResponseTeam;
  roles?: string[] | null;
  emailConfirmed?: boolean;
}
