/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * WebApp
 * OpenAPI spec version: v1
 */

export interface ViewUserResponse {
  id?: string | null;
  userName?: string | null;
  teamId?: number | null;
}
