/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * WebApp
 * OpenAPI spec version: v1
 */
import type { ViewTeamResponseUser } from './viewTeamResponseUser';

export interface ViewTeamResponse {
  id?: number;
  name?: string | null;
  points?: number;
  creatorId?: string | null;
  members?: ViewTeamResponseUser[] | null;
  createdAt?: string;
  updatedAt?: string;
}
