/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * WebApp
 * OpenAPI spec version: v1
 */
import type { ViewContestEntryResponseCorrection } from './viewContestEntryResponseCorrection';
import type { ViewContestEntryResponseTeam } from './viewContestEntryResponseTeam';

export interface ViewContestEntryResponse {
  id?: number;
  correction?: ViewContestEntryResponseCorrection;
  team?: ViewContestEntryResponseTeam;
}
