name: Deploy to production server
run-name: ${{ github.actor }} is doing a deployment to production 🛸
on: "workflow_dispatch"
jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-🛸"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz --ignore-errors ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/CreativeScienceTournament
      - name: Run deploy script on server
        if: success() || failure()
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "bash /home/${{ secrets.SSH_USER }}/CreativeScienceTournament/deploy.sh"